services:
  agent:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: agent
    ports:
      - "12345:12345"
    networks:
      - my_network

networks:
  my_network:
    external: true
